name: coverage

on:  [pull_request]

jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    env:
      ENV: development
      SECRET: secret
      JWT_SALT: 10
      JWT_EXPIRE: 3h

    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}      

      - name: Install npm dependencies
        run: npm ci

      - name: Run Jest
        run: yarn jest --coverage

      - name: Show coverage in comments
        uses: romeovs/lcov-reporter-action@v0.2.17
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: ./coverage/lcov.info
